### PR TITLE
implement concatmap, flatmap, switchmap operators

### PR DESCRIPTION
**Pull request by SillyFreak**
Add API proposed in issue #3

### CODE REVIEW

**Comment by vxgmichel** [comment]
Thanks for the PR! I improved the test loop implementation so the tests can run as expected.

**Comment by SillyFreak** [comment]
docs to follow; the one thing to determine is whether `concat`, `flat`, `switch` should be public APIs. I'm leaning to yes, but `flat` should probably be `flatten` then, and I'll have a look if that matches e.g. Haskell's list APIs (which I think it does).

**Comment by vxgmichel** [comment]
Great work, It's really appreciated! :D

> the one thing to determine is whether concat, flat, switch should be public APIs. 

I don't have a strong opinion. My first idea was to keep them as internals operators, since it seems unlikely that users need to manually deal with asynchronous sequences of asynchronous sequences (e.g. flatmap and Co. conveniently abstract this part for them).

> I'm leaning to yes, but flat should probably be flatten then, and I'll have a look if that matches e.g. Haskell's list APIs (which I think it does).

I'm fine with both, and I agree we should try to match existing APIs

**Comment by SillyFreak** [comment]
I just realized - looking at this from the docs: "Note: `map` is considered a combination operator if used with extra sources, and a transformation operator otherwise" - all this code should really be in `transform.py`, right? :'D

I think apart from adding some `.. autoclass::` lines to the docs, that's it, right? I'll leave the (potential) moving to you!

**Comment by vxgmichel** [comment]
> I think it's reasonable to make all three public APIs

My only concern about this is that users might get confused by:
- `concat` vs `chain`
- `flatten` vs `merge`

Maybe we could create a new category for streams of streams, gathering:
- `concat` and `concatmap`
- `flatten` and `faltmap`
- `switch` and `switchmap`

and make it obvious that those are **advanced** operators.

What do you think? :)

> I haven't added explicit tests, as they are covered already. Is that fine with you?

Yea, as long as we keep the 100% coverage rate. I might add more tests later on.

> I just realized - looking at this from the docs: "Note: map is considered a combination operator if used with extra sources, and a transformation operator otherwise" - all this code should really be in transform.py, right? :'D

The `map` operator is documented and available in both categories, but since the implementation itself focus more on the combination than the transformation, I put it in `combine.py`. I have no problem with moving it around tho, if you think it'd make more sense!

> I think apart from adding some .. autoclass:: lines to the docs, that's it, right? 

Yep, and `table.rst.inc` also needs to be updated!

Also, I'm planning to refactor the `switch` implementation a bit (the same way I've done it for `flatten`), please fell free to review it if you think some aspects could be improved.

**Comment by SillyFreak** [comment]
> Maybe we could create a new category for streams of streams

I don't know how to call that category, but that would make the most sense for sure! My thoughts about moving were because at least the `concat`, `flatten` and `switch` operators (not the `*map` ones though) take one stream and produce one stream, i.e. transform. But as they require streams _of streams_, they're really something different, giving them their own module sounds better. The `*map` variants also belong there in my opinion, I think that's both the expectation from the function names, and reasonable because the mapping function is restricted to return streams/iterables.

**Comment by vxgmichel** [comment]
> I don't know how to call that category, but that would make the most sense for sure! 

It seems wikipedia is calling streams of streams [streams of higher order](https://en.wikipedia.org/wiki/Reactive_programming#Higher-order_reactive_programming), though I can't find a good related name for the corresponding category. 

Right now I'm leaning toward `advanced`. We can find a better name later on if we end up with some other advanced operators of a different nature.

Would you like to create this category, or should I take care of it? :)

**Comment by SillyFreak** [comment]
If `higher_order` weren't so clunky... Please go ahead :)

**Comment by vxgmichel** [comment]
@SillyFreak Done! Do you want to review the changes before I merge it?

**Comment by SillyFreak** [comment]
Looks good, nothing to add from me!

**Comment by vxgmichel** [comment]
Thanks again for your help! Advanced operators will become available with version `0.2.5`.

**Comment by vxgmichel** [comment]
Hi @SillyFreak, you might be interested in PR #10 and [v0.3.0](https://github.com/vxgmichel/aiostream/releases/tag/v0.3.0), cheers!

**Pull request merged**
