### PR TITLE
chore/format/ci: use black stable style 2024; bump flake8 version; add black config to pyproject.toml

### PR DESCRIPTION
**Pull request by hf-kklein**

### CODE REVIEW

**Review by vxgmichel — CHANGES_REQUESTED** [review]
Thanks a lot for taking the time to create this PR, it's much appreciated :)

Why change the line length to 80 though? The default 88 looked fine to me.

**Comment by hf-kklein** [comment]
> Why change the line length to 80 though?

i don't know. this branch was stale for a while. changed it back to 88 now. https://github.com/vxgmichel/aiostream/pull/100/commits/aa2c49f72d7ecd2cd721bd0764562c8cc5ebac97

**Comment by vxgmichel** [comment]
The back and forth between 80 and 88 max length caused more changes than necessary.

I pushed those changes and migrated the rest of setup.cfg in PR #103.

Thanks for your valuable help :)

**Comment by hf-kklein** [comment]
> The back and forth between 80 and 88 max length caused more changes than necessary.

that's unexpected, because I thought black was so uncompromising, that the result would be reproducible even when switching between different lengths. but I don't mind ;)

**Pull request closed without merging**
