### PR TITLE
Added group_by clause in stream aggregation

### PR DESCRIPTION
**Pull request by sourcepirate**
Added a group by method to list a tuple of groups and items.

### CODE REVIEW

**Comment by vxgmichel** [comment]
Hi @sourcepirate, and thank you for making this PR!

Isn't the following approach simpler though?
```python
values = await xs.list()
groups = groupby(values, key)
```
(where `groupby` is one of the synchronous approaches listed [here](https://stackoverflow.com/a/3749537/2846140))

In the case where `key` is an async function, you can still do something like this:
```python
async def add_key(value):
    return (await key(value), value)

ys = stream.map(xs, add_key)
values = await ys.list()
groups = groupby(values, itemgetter(0))
```

**Comment by sourcepirate** [comment]
It looks good @vxgmichel . But it returns a async generator object.
I am not sure you can call `ys.list()` on the result as it is again a `async_generator`.
Or even if you managed to  get value at `ys` you will still get this
`AttributeError: 'map' object has no attribute 'list'`.

Thanks and Regards.

**Comment by vxgmichel** [comment]
> I am not sure you can call ys.list() on the result as it is again a async_generator

Sorry, I should really remember to test my examples :sweat_smile: 

I just fixed the code in my previous comment.

**Comment by sourcepirate** [comment]
@vxgmichel. Not sure is it ok to use `itertools.grouby`. Since the groupby returns a tuple of `(key, <itertools.grouper>)`. You may have to use an additional list comprehension over value which might be  undesirable. Any thoughts  ?

**Comment by tonal** [comment]
@vxgmichel, @sourcepirate, 
The presented implementation will not be able to work with endless streams.
Before you start anything to give it will need to read the entire stream to the end.
If the input is a large file or TCP stream, the memory will quickly overflow.
In addition, in many cases, algorithms with iterators are used when they are confident that the calculation can be interrupted by reading only a small part of a potentially infinite stream.

It seems to me that an implementation that breaks these concepts should not be included in the library.

**Comment by sourcepirate** [comment]
@tonal So true. I agree. Please share you thoughts on the async implementation idea you have. I can happily do the changes in PR. I am happy to take in your suggestions. Do have any ? I believe from your comment earlier you might have got a strong implementation idea 💯 Please share us you thoughts more to help figure this out.

**Comment by vxgmichel** [comment]
@tonal Thanks for your insight!
I guess it really depends on what we expect from `groupby`. What I initially had in mind is was a simple aggregation operator like `stream.list`, returning a `{<key>: [<item>]}` dictionary. And you're right that this wouldn't work with endless stream, in the same way that `stream.list` doesn't.

But in the specific case of groupby, [itertools](https://docs.python.org/2/library/itertools.html#itertools.groupby) does manage to provide a lazy implementation for this operator so it would make sense for `aiostream` to do the same. However, this version of groupby groups **consecutive** items, so it's quite different from @sourcepirate version of this operator which also groups non consecutive items.

I'd like to go for consecutive grouping, but we still have to decide whether the operator should yield:
- a `(<key>, [<items>])` tuple
   * pro: simple
   * con: leak with operators like `stream.repeat`
- a `(<key>, <stream>)` tuple
  * pro: truly lazy
  * con: hard to implement correctly (no operator in aiostream currently generates other streams)

@sourcepirate @tonal What do you think?

**Comment by sourcepirate** [comment]
@vxgmichel Looks good to me. Since it is consecutive grouping the PR is not relevant for this.
So i shall close the PR.

Thanks

**Pull request closed without merging**
